### ISSUE TITLE
Investigate platform options for runners

### ISSUE THREAD

**Issue by LinuxBozo** [CMSgov/github-actions-runner-aws#2]
In order to provide the most capability and compatibility with third party actions, investigate the best option for platforming of internal runners, ECS/Fargate, ECS/EC2, EKS, and EC2.

Please at least compare:
work required for docker-in-docker (for fargate/eks)
scaling
ease of deployment
ease of upgrade paths (CVE, etc)
ease of clean up between action runs
(Add more points in the requirements as fitting)

Acceptance: We have an ADR with the final recommendation ready for review and final sign off.

**Comment by lxuo-trussworks** [comment]
ADR: https://confluenceent.cms.gov/display/CMCSMAC/0007+-+Github+Self-Hosted+Runner+Platform+for+Deployment
