### ISSUE TITLE
Usage of this self-hosted runner

### ISSUE THREAD

**Issue by bijujoseph** [CMSgov/github-actions-runner-aws#64]
I work on QPP (qpp.cms.gov). 
Are we using this within CMS ? If yes, which team ? I would like to see if this can bed used for my projects. 
We recently had an outage as described in: https://jira.cms.gov/browse/WHSD-40581, https://jira.cms.gov/browse/TOOLS-4899
My EUA is J5D6, If you can pass me yours, I can look you up on Slack and start conversation. Thank you!

**Comment by bijujoseph** [comment]
Also there is another one https://qnetgit.cms.gov/HFC/cdk-github-actions-runner inspired from https://github.com/nikovirtala/cdk-github-actions-runner customized for HCQIS AWS environments.

**Comment by crbudzeak** [comment]
Apologies, @bijujoseph, I missed this original notification. This project is being used within CMS by the MACPRO team. I will send you a message in slack as well.
